// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  footer: dynamic(() => import("./Footer")),
  frequently_asked_questions: dynamic(
    () => import("./FrequentlyAskedQuestions"),
  ),
  hero: dynamic(() => import("./Hero")),
  image_slider: dynamic(() => import("./ImageSlider")),
  services: dynamic(() => import("./Services")),
  why_choose_us: dynamic(() => import("./WhyChooseUs")),
};
